INSERT INTO DEVICE_CONNECTION (CONNECTION_NAME, DEVICE_ID, CONNECTION_TYPE_ENUM_ID, PURPOSE_ENUM_ID, DRIVER_ENUM_ID, TRANSPORT_ENUM_ID, TRANSPORT_CONFIG)
VALUES ('VPL_OPCUA_CONN___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DctDirectConnection', 'DcpOperations', 'DcdOpcUa', 'DctrTcp', '__OPCUA_TRANSPORT_CONFIG__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME, POLLING_INTERVAL)
VALUES ('VPL_OPCUA_READ_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtCyclic', 'DrpControl', 'DrrDirect', 'VPL_OPCUA_CONN___SUFFIX__', 100);
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_OPCUA_READ_REQ___SUFFIX__', 'VPL_PARAM_FEEDBACK___SUFFIX__', 1, '__OPCUA_FEEDBACK_NODE__');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_OPCUA_READ_REQ___SUFFIX__', 'VPL_PARAM_FAULT___SUFFIX__', 2, '__OPCUA_FAULT_NODE__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, PARENT_REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME)
VALUES ('VPL_OPCUA_UNSUB_REQ___SUFFIX__', 'VPL_OPCUA_READ_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtUnsubscribe', 'DrpControl', 'DrrDirect', 'VPL_OPCUA_CONN___SUFFIX__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME, ONLY_CHANGED_PARAMETERS)
VALUES ('VPL_OPCUA_WRITE_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtWrite', 'DrpControl', 'DrrDirect', 'VPL_OPCUA_CONN___SUFFIX__', 'N');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_OPCUA_WRITE_REQ___SUFFIX__', 'VPL_PARAM_REFERENCE___SUFFIX__', 1, '__OPCUA_REFERENCE_WRITE_NODE__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME)
VALUES ('VPL_OPCUA_ONESHOT_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtRead', 'DrpControl', 'DrrDirect', 'VPL_OPCUA_CONN___SUFFIX__');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_OPCUA_ONESHOT_REQ___SUFFIX__', 'VPL_PARAM_FEEDBACK___SUFFIX__', 1, '__OPCUA_FEEDBACK_NODE__');
